# Generated by Django 3.2.5 on 2021-07-07 09:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sst', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='user_id',
            field=models.CharField(default='sst21', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 7, 14, 47, 48, 515976)),
        ),
    ]
