# Generated by Django 3.2.5 on 2021-07-07 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sst', '0003_auto_20210707_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdetails',
            name='q_papper',
            field=models.FileField(default='', upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='testdetails',
            name='total_marks',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='testdetails',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 7, 16, 41, 36, 921606)),
        ),
    ]
