# Generated by Django 3.2.5 on 2021-07-07 11:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sst', '0004_auto_20210707_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_name', models.CharField(max_length=50, verbose_name='Exam')),
                ('q_paper', models.FileField(upload_to='q_papers')),
            ],
        ),
        migrations.RemoveField(
            model_name='testdetails',
            name='q_papper',
        ),
        migrations.AlterField(
            model_name='testdetails',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 7, 17, 6, 50, 285329)),
        ),
    ]
