# Generated by Django 3.2.5 on 2021-07-07 12:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sst', '0005_auto_20210707_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdetails',
            name='class_name',
            field=models.CharField(default='seventh', max_length=50, verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='testdetails',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 7, 17, 30, 35, 608341)),
        ),
    ]
