# Generated by Django 3.2.5 on 2021-07-07 12:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sst', '0006_auto_20210707_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='testpaper',
            name='published_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='testdetails',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 7, 18, 29, 1, 784241)),
        ),
        migrations.AlterField(
            model_name='testpaper',
            name='q_paper',
            field=models.FileField(upload_to='q_papers/%Y/%m/%d'),
        ),
    ]
