# Generated by Django 3.2.5 on 2021-07-07 15:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sst', '0009_auto_20210707_2039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testpaper',
            options={'ordering': ['-created_on']},
        ),
        migrations.AddField(
            model_name='testpaper',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 7, 20, 41, 31, 504453)),
        ),
        migrations.AlterField(
            model_name='testdetails',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 7, 20, 41, 31, 504453)),
        ),
    ]
