# Generated by Django 3.2.5 on 2021-07-08 09:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sst', '0010_auto_20210707_2041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testpaper',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='testdetails',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 8, 14, 56, 32, 448763)),
        ),
        migrations.AlterField(
            model_name='testpaper',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 8, 14, 56, 32, 447767)),
        ),
    ]
