# Generated by Django 3.2.5 on 2021-07-08 09:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sst', '0011_auto_20210708_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testdetails',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 8, 15, 9, 25, 43356)),
        ),
        migrations.AlterField(
            model_name='testpaper',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 8, 15, 9, 25, 43356)),
        ),
        migrations.AlterField(
            model_name='testpaper',
            name='q_paper',
            field=models.FileField(upload_to='q_papers/%y/%m/%d'),
        ),
    ]
