# Generated by Django 3.2.5 on 2021-07-07 01:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('title_tag', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('category', models.CharField(max_length=250)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2021, 7, 7, 7, 5, 28, 395972))),
                ('views', models.IntegerField(default=0)),
                ('published_status', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Blogs',
            },
        ),
    ]
