# Generated by Django 3.2.5 on 2021-07-07 02:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='content_tag',
            field=models.TextField(default='ajay'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 7, 7, 55, 46, 980358)),
        ),
    ]
