# Generated by Django 3.2.5 on 2021-07-07 12:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_blog_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 7, 17, 30, 35, 600504)),
        ),
    ]
