# Generated by Django 3.2.5 on 2021-07-08 09:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_blog_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 8, 15, 9, 25, 39371)),
        ),
    ]
